name: Terraform deployment for VPC
# List of Actions
on: [push]
jobs:
  terraform-deployment:
    runs-on: ubuntu-latest
    # Steps is a List and each element is defined with a dash
    steps:
      #EXPORT THE CREDENTIALS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-central-1"
      
      - name: Clone/Checkout your repository code
        uses: actions/checkout@v2
      
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve