name: Terraform deployment for VPC
# List of Actions
on: [push]
jobs:
  terraform-deployment:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
      # Steps is a List and each element is defined with a dash
    steps:
      # EXPORT THE CREDENTIALS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::041308375526:role/github-actions-oidc
          aws-region: "eu-central-1"

      - name: Clone/Checkout your repository code
        uses: actions/checkout@v2

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v1

      - name: Terraform init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Apply the changes
        run: terraform apply -auto-approve